language: php

php:
 - 5.3

env:
  global:
  - DATABASE='drupal'
  - DB_USERNAME='root'
  - DB_ENCODE='utf8'
  - MODULE_PATH='build/profiles/d7_usao_edu'
  - secure: S4sWH3Ov7j3r700JBa4cFmohDQOX45fUFlzxxVI2z7EVXiIXBeh6bu1LoMYpdpgtf+sIc6Q3gR2QYeuyaS0Lf8BTAQ+0YCla6SHL2nJPKO2YEz/v8t1VkAgu51d/2LB37/U0xAyxXN/6cxJAn1YTdeGFz7TXD1mJvlaF7J5Y6xU=
  - secure: aHMiT+r9f5UssrKLFOlyBnOfLOpbbQjkWgRy1xqrROhf5dReUY7gdLqHvRw4J+tmcFlp4K/1/MjFVLb1fgha4DxKng9bQmqxGTS9YMuakAoz4Zhce6bXYF2I/aIchj0AR7zQFzAdTh1mW7vGkUfPFdNyjQCUrExm55LeTeNISY0=
  
mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
 - bash -v travis_before_install.sh
 - curl -I http://ftp.drupal.org/files/projects/drupal-7.32.tar.gz --verbose
 - sudo apt-get update > /dev/null
 - composer self-update

install:
 - sudo apt-get install -y --force-yes php5-cgi php5-mysql php5-curl
 - composer install --prefer-source
 - phpenv rehash

before_script:
 - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'display_errors = stdout' >>
   ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
 - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'log_errors = 1' >> ~/.phpenv/versions/$(phpenv
   version-name)/etc/conf.d/travis.ini; fi
 - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'error_log = syslog' >> ~/.phpenv/versions/$(phpenv
   version-name)/etc/conf.d/travis.ini; fi
 - if [[ "$TRAVIS_PHP_VERSION" != hhvm* ]]; then echo 'sendmail_path = /bin/true' >>
   ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
 - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo -e 'sendmail_path = /bin/true'
   | sudo tee -a /etc/hhvm/php.ini; fi
 - mysql -e 'create database drupal;'
 - echo "Host bitbucket.org" >> ~/.ssh/config
 - echo "   Hostname bitbucket.org" >> ~/.ssh/config
 - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
 - echo "   CheckHostIP no" >> ~/.ssh/config
 - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
 - git config --global user.email "travis@usao.edu"
 - git config --global user.name "Travis the Build Bot"
 - $TRAVIS_BUILD_DIR/vendor/bin/drush make --yes d7_usao_edu.core build
 - mkdir -p $MODULE_PATH
 - git archive $(git rev-parse --abbrev-ref HEAD) | tar -x -C $MODULE_PATH
 - cp -r $TRAVIS_BUILD_DIR/modules $MODULE_PATH
 - cp -r $TRAVIS_BUILD_DIR/themes $MODULE_PATH
 - cp -r $TRAVIS_BUILD_DIR/d7_usao_edu.profile $MODULE_PATH
 - cp -r $TRAVIS_BUILD_DIR/d7_usao_edu.install $MODULE_PATH
 - cp -r $TRAVIS_BUILD_DIR/d7_usao_edu.info $MODULE_PATH
 - cp -r $TRAVIS_BUILD_DIR/d7_usao_edu.make $MODULE_PATH
 - cd $MODULE_PATH
 - $TRAVIS_BUILD_DIR/vendor/bin/drush make --yes --no-core --contrib-destination=. d7_usao_edu.make
 - $TRAVIS_BUILD_DIR/vendor/bin/drush --yes site-install d7_usao_edu --db-url="mysql://$DB_USERNAME:@127.0.0.1/$DATABASE"
 - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver 127.0.0.1:8080 & until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
 - $TRAVIS_BUILD_DIR/vendor/bin/drush --yes en syslog
 - $TRAVIS_BUILD_DIR/vendor/bin/drush cc all --yes
 - $TRAVIS_BUILD_DIR/vendor/bin/drush cron
 - mkdir -p $TRAVIS_BUILD_DIR/build/logs

script:
 - test -d $TRAVIS_BUILD_DIR/build/profiles/d7_usao_edu/modules/contrib
 - test -d $TRAVIS_BUILD_DIR/build/profiles/d7_usao_edu/modules/custom
 # - phpunit --coverage-clover $TRAVIS_BUILD_DIR/build/logs/clover.xml --verbose --debug

after_script:
 - cd $TRAVIS_BUILD_DIR
 # - php $TRAVIS_BUILD_DIR/vendor/bin/coveralls -v
 - $TRAVIS_BUILD_DIR/vendor/bin/phpmd $TRAVIS_BUILD_DIR/$MODULE_PATH text codesize,naming,design --exclude modules,themes
 - $TRAVIS_BUILD_DIR/vendor/bin/phpcpd $TRAVIS_BUILD_DIR/$MODULE_PATH --exclude modules --exclude themes
 - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=$TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal --ignore=modules,themes
 - $TRAVIS_BUILD_DIR/$MODULE_PATH

after_failure:
 - sudo cat /var/log/syslog

notifications:
 irc: irc.freenode.org#cdracars
