language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make d7_usao_edu.build ../d7_dev.usao.edu
  - cd ../d7_dev.usao.edu
  - sudo chmod _dev-R 777 sites/
  - drush si d7_usao_edu --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=USAO@2012 --site-mail=admin@example.com --site-name="d7.usao.edu" --yes
  - drush cc all --yes

script:
  - test -d profiles/d7_usao_edu
